### ISSUE TITLE
Images require visual guides

### ISSUE THREAD

**Issue by EstebanDalelR** [approachable-io/software-interview-prep#5]
Images are really good quality but give no hints as to that to do. Maybe cirles or arrows pointing to the actions to be used?

**Comment by redxtech** [comment]
All the directions are in the text, and the images just show what it should look like when you follow those directions.

Are there any specific cases where the images need circle or arrows?

The ones on the github website seem like the only ones that might benefit from some extra info, but they seem self explanatory enough to me, but maybe that's because I added them.

**Comment by LukeSchlangen** [comment]
Closing for now. Will reopen if there are specific examples that need improvement. Feel free to make a PR as well.
